version: "3.9"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - /tmp/otel-collector-config.yaml:/etc/otel/config.yaml
    command: --config /etc/otel/config.yaml
    environment:
      - JAEGER_ENDPOINT=jaeger:4317
      - METRIC_ENDPOINT=${METRIC_ENDPOINT:-"http://localhost:4318/v1/metrics"}
    ports:
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4318:4318"   # OTLP HTTP receiver
      - "4317:4317"   # OTLP gRPC receive
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.46.0
    ports:
      - "16686:16686" # Jaeger Web UI

