receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

connectors:
  spanmetrics:

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
    headers:
      Authorization: "Basic ${JAEGER_AUTH_TOKEN}"
  prometheusremotewrite:
    endpoint: "${METRIC_ENDPOINT}"

extensions:
  health_check:
  zpages:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]
